version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - kafka_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAMES: INSIDE,OUTSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9094
      KAFKA_LISTENER_INTERNAL: INSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - "9093:9093"
      - "9094:9094"
    depends_on:
      zookeeper:
        condition: service_healthy

    networks:
      - kafka_network
    volumes:
      - kafka-data:/var/lib/kafka
    entrypoint: /etc/confluent/docker/run

  kafka-manager:
    image: hlebalbau/kafka-manager:latest
    environment:
      ZK_HOSTS: "zookeeper:2181"
    ports:
      - "9000:9000"
    depends_on:
      - kafka
    networks:
      - kafka_network

  vitals-producer:
    build:
      context: ./apps/producers/retrieve-vitals
    container_name: retrieve-vitals
    environment:
      - KAFKA_BROKER=kafka:9093
      - KAFKA_TOPIC=vitals
    ports:
      - "8081:8080"
    depends_on:
      - kafka
      - zookeeper
    networks:
      - kafka_network
    command: ["python", "app.py"]

  vital-timeseries-consumer:
    build:
      context: ./apps/consumers/vital-timeseries
    container_name: vital-timeseries-consumer
    environment:
      - KAFKA_BROKER=kafka:9093
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=vitals
      - INFLUXDB_ORG=pst
      - INFLUXDB_TOKEN=asAai14oqZiRQ_jdtFj6ZQUZ1pdI8Sb6d4rUwHyKTzBbUUjrUGMFIgj-AJLCHD5mf3mM6LjbSrsc8vWHTuZ1bA==
    depends_on:
      - kafka
      - influxdb
    networks:
      - kafka_network
    volumes:
      - ./apps/consumers/vital-timeseries:/app

  influxdb:
    image: influxdb:latest
    environment:
      - KAFKA_BROKER=kafka:9093
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=vitals
      - INFLUXDB_ORG=pst
      - INFLUXDB_TOKEN=asAai14oqZiRQ_jdtFj6ZQUZ1pdI8Sb6d4rUwHyKTzBbUUjrUGMFIgj-AJLCHD5mf3mM6LjbSrsc8vWHTuZ1bA==
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - kafka_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

networks:
  kafka_network:
    driver: bridge

volumes:
  kafka-data:
  influxdb-data:
